### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by conao3** [hotoku/zetasql-formatter-el#1]
Please add LICENSE file on this repository?
ref: [ライセンスをつけないとどうなるの？- qiita](https://qiita.com/Tatamo/items/ae7bf4878abcf0584291)

For example
- GPL v3 (Emacs is released under this license, and many Emacs packages are released under this license.)
- MIT (A permissive license that only requires the display of your name.)
- CC0 (All rights are hereby waived and declared to be in the public domain.)

**Comment by hotoku** [comment]
@conao3 Thank you for your pointing out.

In this commit, I added a declaration of MIT license.
https://github.com/hotoku/zetasql-formatter-el/commit/b66fcb37abbd9b23555621928d6f24f2855dede0
